"""Add subscribers table
Revision ID: 12c9b8025fde
Revises: 21c151c5657a
Create Date: 2018-02-13 23:57:06.421684
"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '12c9b8025fde'
down_revision = '21c151c5657a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('subscribe',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('subscribe')
    # ### end Alembic commands ###
