lines (26 sloc)  1.09 KB
"""Add relationship
Revision ID: 21c151c5657a
Revises: 8cc9557c4f82
Create Date: 2018-02-13 19:51:52.918309
"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '21c151c5657a'
down_revision = '8cc9557c4f82'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('blogs_comment_id_fkey', 'blogs', type_='foreignkey')
    op.drop_column('blogs', 'comment_id')
    op.add_column('comments', sa.Column('blog_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'comments', 'blogs', ['blog_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'comments', type_='foreignkey')
    op.drop_column('comments', 'blog_id')
    op.add_column('blogs', sa.Column('comment_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('blogs_comment_id_fkey', 'blogs', 'comments', ['comment_id'], ['id'])
    # ### end Alembic commands ###
