"""Add name to comments table
Revision ID: 003fb9863606
Revises: 1b0ca371f574
Create Date: 2018-02-13 12:07:20.510308
"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '003fb9863606'
down_revision = '1b0ca371f574'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('name', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('comments', 'name')
    # ### end Alembic commands ###
