"""add column for confirmation and roles
Revision ID: 95a81e925e61
Revises: f403a6396874
Create Date: 2018-02-11 19:54:38.350230
"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '95a81e925e61'
down_revision = 'f403a6396874'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('confirmed', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'confirmed')
    # ### end Alembic commands ###
