"""Add relationship
Revision ID: 8cc9557c4f82
Revises: 5356a9089d2e
Create Date: 2018-02-13 19:08:31.386204
"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8cc9557c4f82'
down_revision = '5356a9089d2e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blogs', sa.Column('comment_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'blogs', 'comments', ['comment_id'], ['id'])
    op.drop_constraint('comments_blog_id_fkey', 'comments', type_='foreignkey')
    op.drop_column('comments', 'blog_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('blog_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('comments_blog_id_fkey', 'comments', 'blogs', ['blog_id'], ['id'])
    op.drop_constraint(None, 'blogs', type_='foreignkey')
    op.drop_column('blogs', 'comment_id')
    # ### end Alembic commands ###
