"""Add name to comments table
Revision ID: 5356a9089d2e
Revises: 003fb9863606
Create Date: 2018-02-13 17:20:00.137946
"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5356a9089d2e'
down_revision = '003fb9863606'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blogs', sa.Column('user_id', sa.Integer(), nullable=True))
    op.drop_constraint('blogs_author_id_fkey', 'blogs', type_='foreignkey')
    op.create_foreign_key(None, 'blogs', 'users', ['user_id'], ['id'])
    op.drop_column('blogs', 'author_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blogs', sa.Column('author_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'blogs', type_='foreignkey')
    op.create_foreign_key('blogs_author_id_fkey', 'blogs', 'users', ['author_id'], ['id'])
    op.drop_column('blogs', 'user_id')
    # ### end Alembic commands ###
